Resources:
  NumbersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.tableName}
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      # Set the capacity to auto-scale
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
